CONFIGURATION:
  urlfortelemetry: http://192.168.1.100:25555/api/ets2/telemetry  # the telemetry server's access url
  arduinoport: COM3                                               # the arduino board's port (check arduino IDE)
  debugmode: False                                                # set if the console returns debug lines (True/False)